server:
  port: 8888

spring:
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    url: jdbc:h2:mem:PriceDatabase
  h2:
    console.enabled: true
    console.path: /h2-console